branch-defaults:
  master:
    environment: weblogo-dev
global:
  application_name: weblogo
  default_ec2_keyname: null
  default_platform: Python 3.4
  default_region: us-west-2
  profile: eb-cli
  sc: git
